# Generated by Django 3.2.19 on 2023-06-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_cost', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_proposal', to='users.profile')),
            ],
        ),
    ]
